### ISSUE TITLE
Furo no carro X

### ISSUE THREAD

**Issue by rodrigopitanga** [Metamaquina/Metamaquina2#102]
O furo para fixação do extrusor no carro X voltado para a parte de trás deve ser uma fenda, e não um furo.

Isso permitirá que o parafuso M4x25 seja fixado na porca antes de o motor ser colocado no bloco extrusor, o que facilitaria muito a montagem do extrusor no carro posteriormente.

**Comment by felipesanches** [comment]
foi implementado na revisão D
