### ISSUE TITLE
Cabeamento do cabeçote extrusor fica muito próximo do motor da extrusora

### ISSUE THREAD

**Issue by gui7vaz** [Metamaquina/Metamaquina2#118]
Hj coloquei a mão na fiação e não dava nem para encostar o dedo de tão quente.
Isso pode ser um perigo. Vou até fazer um seguro pro meu apartamento.
Soltei um pouco os cabos de modo que eles ficassem bem distantes do motor.

**Comment by felipesanches** [comment]
O super-aquecimento dos motores do extrusor foram corrigidos em 2013. Tratava-se de uma configuração errada de corrente do driver de motor de passo.
